/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.cpp
 #	source generated by 4D Plugin Wizard
 #	Project : open-external-dialog
 #	author : miyako
 #	2015/03/10
 #
 # --------------------------------------------------------------------------------*/


#include "4DPluginAPI.h"
#include "4DPlugin.h"

void PluginMain(PA_long32 selector, PA_PluginParameters params)
{
	try
	{
		PA_long32 pProcNum = selector;
		sLONG_PTR *pResult = (sLONG_PTR *)params->fResult;
		PackagePtr pParams = (PackagePtr)params->fParameters;

		CommandDispatcher(pProcNum, pResult, pParams); 
	}
	catch(...)
	{

	}
}

void CommandDispatcher (PA_long32 pProcNum, sLONG_PTR *pResult, PackagePtr pParams)
{
	switch(pProcNum)
	{
// --- Open External Dialog

		case 1 :
			Run_modal_dialog(pResult, pParams);
			break;

	}
}

// ----------------------------- Open External Dialog -----------------------------

typedef PA_long32 method_id_t;

void Run_modal_dialog(sLONG_PTR *pResult, PackagePtr pParams)
{
    C_TEXT Param1;
    C_TEXT Param2;
    C_TEXT Param3;
    C_LONGINT Param4;
    C_LONGINT returnValue;
    
    Param1.fromParamAtIndex(pParams, 1);
    Param2.fromParamAtIndex(pParams, 2);
    Param3.fromParamAtIndex(pParams, 3);
    Param4.fromParamAtIndex(pParams, 4);

    method_id_t methodId = PA_GetMethodID((PA_Unichar *)Param3.getUTF16StringPtr());
    
    if(methodId){
        
        PA_Dial4D dialogId = PA_NewDialog();
        
        PA_OpenDialog(dialogId, 
                      (PA_Unichar *)Param1.getUTF16StringPtr(), //form name
                      (PA_Unichar *)Param2.getUTF16StringPtr(), //window title
                      0, //is there any way to capture the close button?
                      (PA_WindowLevel)Param4.getIntValue());
        
        int dialogStatus;
        PA_Unichar variableName[256];
        
        PA_Variable params[2];
        params[0] = PA_CreateVariable(eVK_Unistring);		
        params[1] = PA_CreateVariable(eVK_Longint);
        
        do {
            
            PA_YieldAbsolute();
            
            dialogStatus = PA_ModalDialog(dialogId, variableName);  
            
            PA_Unistring u = PA_CreateUnistring(variableName);
            
            PA_SetStringVariable(&params[0], &u);
            PA_SetLongintVariable(&params[1], dialogStatus);
            
            PA_Variable returnValue = PA_ExecuteMethodByID(methodId, params, 2);
            
            if(PA_GetVariableKind(returnValue) == eVK_Longint){
                switch (PA_GetLongintVariable(returnValue)) {
                    case 0:
                        dialogStatus = 0;//dialog
                        break;
                    case 1:
                        dialogStatus = 1;//accept
                        break;                        
                    default:
                        dialogStatus = 2;//cancel
                        break;
                };
            }
            
            PA_DisposeUnistring(&u);
            
        } while (dialogStatus == 0);
        
        PA_ClearVariable(&params[0]);
        PA_ClearVariable(&params[1]); 
        
        PA_CloseDialog(dialogId);
        
    }
    
	Param3.toParamAtIndex(pParams, 3);
	returnValue.setReturn(pResult);
}

