/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.h
 #	source generated by 4D Plugin Wizard
 #	Project : open-external-dialog
 #	author : miyako
 #	2015/03/10
 #
 # --------------------------------------------------------------------------------*/



// --- Open External Dialog
void Run_modal_dialog(sLONG_PTR *pResult, PackagePtr pParams);
